language: node_js
script: ./deploy.sh
node_js:
  - node

deploy:
  provider: pages
  cleanup: false
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  fqdn: journal.mees.io
  local_dir: ./journal/public
